### ISSUE TITLE
Difference between friends-of-contao and heimrichhannot?

### ISSUE THREAD

**Issue by Aybee** [heimrichhannot/contao-privacy#1]
Hello, if I search in the packages for "privacy", then I get this extension and this one here https://github.com/friends-of-contao/contao-privacy

As those extension have the same name, what is the difference, or what should one take?

**Comment by Defcon0** [comment]
Hello,

which module fits your needs more is up to you, of course. You can read about the support features for our module in [README.md](https://github.com/heimrichhannot/contao-privacy/blob/master/README.md).

Currently the main features of our module (which works for Contao 3 and 4) are the privacy protocol (for saving all privacy relevant interactions like opt in, opt out, delete, create, ...) and the backend opt in form for invite people to opt in (useful if you gathered contacts on some event and want to include them into your newsletter in a GDPR-commpatible manner).

It mainly depends which functionality you need. Maybe you can use both modules ;-)

**Comment by Aybee** [comment]
Thanx a lot. I will definitely take a look at both extensions.
