### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by frambambulus** [heimrichhannot/contao-privacy#5]
Ist für dieses Plugin der Support unter PHP 8.x angedacht bzw. funktioniert das Ganze schon? Der Contao Installer bricht den Install ja wegen fehlendem PHP-Support ab.

**Comment by koertho** [comment]
For Contao 4 and php 8 please use https://github.com/heimrichhannot/contao-privacy-bundle. 
We should add this info to the readme :)

**Comment by frambambulus** [comment]
Not sure if I'm blind, but there is no such "bundle" plugin. The link also leads to a "Page not found". Do you mean the [Privacy API Bundle](https://github.com/heimrichhannot/contao-privacy-api-bundle)?

**Comment by koertho** [comment]
Oh, I oversaw this is private. Sorry!

**Comment by koertho** [comment]
I need to consult with my colleagues.

**Comment by koertho** [comment]
Hi, I just made the bundle public: https://github.com/heimrichhannot/contao-privacy-bundle

But we can currently not provide much support, pre-christmas chaos ;)
